### ISSUE TITLE
numba and classes

### ISSUE THREAD

**Issue by danielcsaba** [QuantEcon/Distributions.py#1]
Hi John,

it seems that we have a couple of issues with numba's functionality within classes. I'm using numba version 0.26.

The decorators `@jit` and `@vectorized` are not working when they are called from within a class--I think the main problem is with type inference applied to `self`.
I could apply the `@jitclass` outside of the class and leaving the methods inside intact but the achieved performance is at the same order as before.

So it seems, that in order to gain performance we will have to define the `@jit`-ted and `@vectorize`-d functions outside the class and then call them.

I've just discussed with Spencer and we agreed that it would be great to see which approach actually works with the `rmath` functions and which one gives us better performance relative to what we already have in `distcan`.

For this end, I would try and work out one class method with all the different approaches:
- a top level `@jit` 
- a top level `@vectorize` 
- inside a `@jitclass`, 
- inside a `@jitclass` but calling out to the top level `@vectorize`
- using `distcan`

Then we could decide which approach we want to take.

**Comment by spencerlyon2** [comment]
I think from the content of your comparison notebook [here](https://github.com/QuantEcon/Distributions.py/blob/dan_branch/py/approaches_compared.ipynb) that implementing a system where we `@jitclass` a class that simply calls out to `@vectorize`d functions is the way to go. 

In that notebook can you add a line that tests the `@vectorize` functions at a single point? It would be great if we could not have to do both the `@jit` for scalar evaluation and `@vectorize` for vectorized.

Do you have a clear vision for how we can automate this in the build_rmath.py script?

**Comment by danielcsaba** [comment]
I agree, `@vectorize` it is. I've just pushed the extended version with the `@vectorize`-d function evaluated at a single point. The efficiency loss relative to `@jit` is minor (it even switches directions in the cell before the comparison table).

For the first glance, I don't think it should be too complicated to modify the build_rmath.py file accordingly. I would organize according to distributions for better readability (first `@vectorized` rmath functions and then the class calling them for a distribution, then repeat). I'll look into it to figure out the details.

**Comment by spencerlyon2** [comment]
Ok great, I’m glad we can just do @vectorize.

I’m looking forward to your progress on this




// Spencer

On June 6, 2016 at 10:12:24 AM, Daniel Csaba (notifications@github.com)
wrote:

I agree, @vectorize it is. I've just pushed the extended version with the
@vectorize-d function evaluated at a single point. The efficiency loss
relative to @jit is minor (it even switches directions in the cell before
the comparison table).

For the first glance, I don't think it should be too complicated to modify
the build_rmath.py file accordingly. I would organize according to
distributions for better readability (first @vectorized rmath functions and
then the class calling them for a distribution, then repeat). I'll look
into it to figure out the details.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/QuantEcon/Distributions.py/issues/1#issuecomment-224023808>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA9J3MHFI14-YJ5NSGRu5lrLq-fpmX7oks5qJFT3gaJpZM4It0Uv>
.

**Comment by danielcsaba** [comment]
I have pushed an initial version of the `build_rmath.py` file which could potentially be used to write out the univariate distributions. I also added a test of the written `univariate.py` with the Normal and Chisq classes written.

I tried to automate as much of the code as possible--not considering the documentation. For this end I have the following logical blocks in mind:

> a preamble with imports and setting up the `cffi` support. implemented by `_initiate_univariate()`

Then, for each specific distribution three separate blocks:
> a block importing and `@vectorize`-ing the top-level `rmath` functions. implemented by the function `_import_rmath()`

> a block writing out the distribution specific parts which are pulled in from a metadata file. implemented by `_write_class_specific()`

> a block adding and calling the top-level `@vectorize`-d `rmath` functions. implemented by `_write_class_rmath()`
 
The last three steps are repeated for each specific distribution pulling in different metada.

Notes: 
* steps can be merged, now they are treated separately for better readability
* docstrings are still missing -- I thought that these could be copied with slight modification from the `distcan` package. @spencerlyon2, what do you think about that?
* the metadata could be further reduced by for example defining a moment function and then calling that for the variance, skewness, etc..

**Comment by danielcsaba** [comment]
An additional note:
* there is a `RuntimeWarning: divide by zero ...` warning with all the `rmath` functions. Otherwise, they are working fine. Not sure whether shutting the warnings down is wise...

**Comment by spencerlyon2** [comment]
Hey @danielcsaba this is looking good. I have a few comments

- I really like the metadata idea. I'd recommend throwing it into an external yaml or json file.
- I think keeping the steps separate is good (i.e. don't merge them)
- The notebook showed that calling top level `@vectorized` functions from within the class is going to be the way to go. I see that you've done this. My next concern is that if we don't `@jitclass` this version of the class, then we won't be able to use any of these objects in `noPython` mode. Do you know if we can `@jitclass` a class where methods call `@vectorize`d functions?

**Comment by danielcsaba** [comment]
hey @spencerlyon2, regarding your comments:

* I have thrown the metadata into an external yaml file.
* agree with the separate steps
* you are absolutely right, the `@jitclass` decorators were missing by mistake. Indeed, we tested them in a limited way in the comparison notebook and decided to go with that option. I `@jitclass`-ed everything but we have some minor issues. Specifically, the `@jitclass` broke with the original full-fledged classes for two reasons:
    * the `rand` method is using a vararg `*n` which is not supported in `numba`. unfortunately neither default arguments are supported. my current fix for the issue is that we can't call the `rand` method without specifying how many random variables we want to generate. Compared to `Julia` instead of `rand` we have to put `rand(1)`. For n>1 there is no change. This is a little annoyance.
    * `numba` does not support the `scipy.special` functions -- we are using the `digamma` function in defining the entropy of the `Chisq` distribution. For this end I added a python script which contains code for a `@vectorize`-d `digamma` function. If we need to use anything from `scipy.special` we will have to write it up ourselves.

With the mentioned fixes everything seems to work and some initial testing gives a 25-100 times improvement in the running time relative to `scipy.stats` depending on the method.

**Comment by danielcsaba** [comment]
I pushed the updated version to the branch

**Comment by spencerlyon2** [comment]
Looking good. Want to open a pull request for that branch and we can start looking at it more closely?

**Comment by danielcsaba** [comment]
sure, i'll do it now
