### ISSUE TITLE
AttributeError: module 'pysal' has no attribute 'open'

### ISSUE THREAD

**Issue by XiufengLai** [QuantEcon/Distributions.py#30]
![1668774368187](https://user-images.githubusercontent.com/72388159/202704650-c1fe3204-79ae-4673-b9d8-69b299b6cef3.png)

**Comment by knaaptime** [comment]
thanks for the report, could you post an actual traceback? The screenshot doesnt match the error

**Comment by XiufengLai** [comment]
您的邮件已收到，我会尽快查看，祝一切顺利！This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you

**Comment by XiufengLai** [comment]
您的邮件已收到，我会尽快查看，祝一切顺利！This is an automatic reply, confirming that your email was received.I will reply as soon as possible.Thank you
